In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

sample_submission.csv
test.csv
train.csv



In [2]:
train = pd.read_csv('../input/train.csv')

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(min_df=3,stop_words='english',ngram_range=(1,3),max_df=0.7, sublinear_tf=1, lowercase=True)

In [4]:
from sklearn.cross_validation import train_test_split
df_x=train["comment_text"]
df_y=train["insult"]
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

/opt/conda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
x_traincv=cv.fit_transform(x_train)



In [6]:
from sklearn.linear_model import LogisticRegression
clf_lr = LogisticRegression(penalty='l1', verbose=1)
clf_lr.fit(x_traincv,y_train)


[LibLinear]

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=1, warm_start=False)

In [7]:
x_testcv=cv.transform(x_test)
predictions=clf_lr.predict(x_testcv)

In [8]:
a=np.array(y_test)

In [9]:
from sklearn.metrics import confusion_matrix


In [10]:
confusion_matrix(a, predictions)

array([[18074,   164],
       [  425,   508]])

In [11]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(a, predictions)

(array([ 0.97702579,  0.75595238]),
 array([ 0.99100779,  0.54448017]),
 array([ 0.98396712,  0.63302181]),
 array([18238,   933]))

In [12]:
# lets try different values of C
Cs = [0.1, 0.5, 2.0, 4.0, 10.0, 200]

for C in Cs:
    print('C:', C)
    clf_lr = LogisticRegression(penalty='l1', verbose=1, C=C)
    clf_lr.fit(x_traincv,y_train)
    predictions=clf_lr.predict(x_testcv)
    CM = confusion_matrix(a, predictions)
    print('\nConfusion matrix:\n', CM)
    score = precision_recall_fscore_support(a, predictions)
    print('\nprecision_recall_fscore_support:\n', score)
    print('\n===========\n')

C: 0.1
[LibLinear]
Confusion matrix:
 [[18151    87]
 [  596   337]]

precision_recall_fscore_support:
 (array([ 0.96820825,  0.79481132]), array([ 0.99522974,  0.36120043]), array([ 0.98153305,  0.49668386]), array([18238,   933]))


C: 0.5
[LibLinear]
Confusion matrix:
 [[18098   140]
 [  463   470]]

precision_recall_fscore_support:
 (array([ 0.97505522,  0.7704918 ]), array([ 0.99232372,  0.50375134]), array([ 0.98361369,  0.60920285]), array([18238,   933]))


C: 2.0
[LibLinear]
Confusion matrix:
 [[18058   180]
 [  384   549]]

precision_recall_fscore_support:
 (array([ 0.97917796,  0.75308642]), array([ 0.9901305 ,  0.58842444]), array([ 0.98462377,  0.66064982]), array([18238,   933]))


C: 4.0
[LibLinear]
Confusion matrix:
 [[18037   201]
 [  367   566]]

precision_recall_fscore_support:
 (array([ 0.98005868,  0.73794003]), array([ 0.98897905,  0.60664523]), array([ 0.98449866,  0.66588235]), array([18238,   933]))


C: 10.0
[LibLinear]
Confusion matrix:
 [[18021   217]
 [  38

In [13]:
# C = 4 looks like a good value

In [14]:
# lets also try SVC - takes hell lot of a time with so many features...


In [15]:
# from sklearn.svm import SVC
# clf_svc = SVC(kernel = 'linear')

In [16]:
# clf_svc.fit(x_traincv,y_train)

In [17]:
'''
predictions=clf_svc.predict(x_testcv)
CM = confusion_matrix(a, predictions)
print('\nConfusion matrix:\n', CM)
score = precision_recall_fscore_support(a, predictions)
print('\nprecision_recall_fscore_support:\n', score)
'''


"\npredictions=clf_svc.predict(x_testcv)\nCM = confusion_matrix(a, predictions)\nprint('\nConfusion matrix:\n', CM)\nscore = precision_recall_fscore_support(a, predictions)\nprint('\nprecision_recall_fscore_support:\n', score)\n"