In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

sample_submission.csv
test.csv
train.csv



In [2]:
import pandas as pd
df = pd.read_csv('../input/train.csv')

In [3]:
df

id                                       comment_text  toxic  \
0          22256635  Nonsense?  kiss off, geek. what I said is true...      1   
1          27450690  "\n\n Please do not vandalize pages, as you di...      0   
2          54037174  "\n\n ""Points of interest"" \n\nI removed the...      0   
3          77493077  Asking some his nationality is a Racial offenc...      0   
4          79357270  The reader here is not going by my say so for ...      0   
5          82428052      Fried chickens \n\nIs dat sum fried chickens?      0   
6          87311443  Why can you put English for example on some pl...      0   
7         114749757  Guy Fawkes \n\nim a resident in bridgwater and...      0   
8         138560519  as far as nicknames go this article is embarra...      0   
9         139353149  Woodland Meadows\nGood to hear that you correc...      0   
10        150009866  "\n\nWell I just finished a good bit of editin...      0   
11        152276337  Discussion should take place on the article ta...      0   
12        153331729  Uh oh, you called my bluff. I am intimidated b...      0   
13        153600803  "\nWe should also contact the living descendan...      0   
14        154186883  " May 2008 (UTC)\n\nNotability of Your New Hea...      0   
15        161894108  "\n\nWhile I agree that this article isn't FA ...      0   
16        169740962  a Turkish citizen and him having received an a...      0   
17        178084608  Please explain why censorship of quality addit...      0   
18        208005265  In any case, this edit war will last forever. ...      0   
19        224733383  "\n\n ""Vandalism"" of George Washington \n\nW...      0   
20        225701312  Why hasn't Alitalia been removed rom the allia...      1   
21        237279459  "\n\n Another AfD stats example \n\nI hope you...      0   
22        254015372  "\nI will ;). How about... ah, I've got nothin...      0   
23        280570905  ":I have moved some tedious detail in ""Survey...      0   
24        284253328  @AnnieHall, what separates this from capitalis...      0   
25        287371884  .  and its also not random, it was the first c...      0   
26        293668009  "\nThe Graceful Slick....\nIs non other than a...      1   
27        300891545  "====Regarding edits made during December 2 20...      0   
28        307040060  "::The section is now called ""Discrepancies a...      0   
29        340940431  "\n\n Smackdown! \n\nGood smackdown on Qatar, ...      0   
...             ...                                                ...    ...   
95821  999674711016  Gods. I'm an Anglo-Norman-ist, really, not an ...      0   
95822  999677373048  "==T. COTTON LETTER TO THE AYATOLLAHS OF IRAN=...      0   
95823  999693619845  Much appreciated \n\nThank you! Yours is my fi...      0   
95824  999714130533  I do apologize once more to you for my unkind ...      0   
95825  999716611707  It has been confirmed that Raul has joined FC ...      0   
95826  999731184003  "\nThat an article is ""more than a definition...      0   
95827  999741263322  Calling someone the archetypical unscientific ...      0   
95828  999744390044  Just pointing out that if you intend to keep a...      0   
95829  999749161210  I'm sorry for not noticing that on the article...      0   
95830  999776197636  Can I just say, no-one cares about your opinio...      0   
95831  999781781533  See Wikipedia:Administrators#Misuse_of_adminis...      0   
95832  999825778693  December 2010\nPlease stop the foolish edits t...      0   
95833  999829405247        Another Unblock Request \n\n 137.240.136.80      0   
95834  999856640855                   so this can finally be over with      0   
95835  999883234532  Oh, okay. Fair enough, then. Thanks for making...      0   
95836  999887342595  "\nI believe you're out of line. You're specul...      0   
95837  999888096837     , 22 April 2007 (UTC)\n\nSecond-hander.  21:45      0   
95838  999898414104         "\nIt's staying. Let

In [4]:
import spacy

In [5]:
import nltk

In [6]:
for ix, row in df[25:50].iterrows():
    print(dict(row), '\n')
    

{'id': 287371884, 'comment_text': '.  and its also not random, it was the first clan/guild on Star Wars Battlefront II for PS2 online.', 'toxic': 0, 'severe_toxic': 0, 'obscene': 0, 'threat': 0, 'insult': 0, 'identity_hate': 0} 

{'id': 293668009, 'comment_text': '"\nThe Graceful Slick....\nIs non other than an ungraceful dick!86.131.154.225  "', 'toxic': 1, 'severe_toxic': 0, 'obscene': 0, 'threat': 0, 'insult': 0, 'identity_hate': 0} 

{'id': 300891545, 'comment_text': '"====Regarding edits made during December 2 2006 (UTC)====\nThank you for experimenting with  Wikipedia. Your test worked, and it has been reverted or removed. Please use the sandbox for any other tests you may want to do. Take a look at the welcome page to learn more about contributing to our encyclopedia. Ω612 \'\'\'ER "', 'toxic': 0, 'severe_toxic': 0, 'obscene': 0, 'threat': 0, 'insult': 0, 'identity_hate': 0} 

{'id': 307040060, 'comment_text': '"::The section is now called ""Discrepancies and inaccuracies"", whi

In [7]:
df.describe()

id         toxic  severe_toxic       obscene        threat  \
count  9.585100e+04  95851.000000  95851.000000  95851.000000  95851.000000   
mean   4.994359e+11      0.096368      0.010068      0.053301      0.003182   
std    2.890136e+11      0.295097      0.099832      0.224635      0.056320   
min    2.225664e+07      0.000000      0.000000      0.000000      0.000000   
25%    2.473437e+11      0.000000      0.000000      0.000000      0.000000   
50%    5.001297e+11      0.000000      0.000000      0.000000      0.000000   
75%    7.501088e+11      0.000000      0.000000      0.000000      0.000000   
max    9.999882e+11      1.000000      1.000000      1.000000      1.000000   

             insult  identity_hate  
count  95851.000000   95851.000000  
mean       0.049713       0.008492  
std        0.217352       0.091762  
min        0.000000       0.000000  
25%        0.000000       0.000000  
50%        0.000000       0.000000  
75%        0.000000       0.000000  
max        1.000000       1.000000

In [8]:
df.corr()

id     toxic  severe_toxic   obscene    threat    insult  \
id             1.000000 -0.000033      0.004019  0.005868 -0.002872  0.003664   
toxic         -0.000033  1.000000      0.308810  0.677491  0.162967  0.648330   
severe_toxic   0.004019  0.308810      1.000000  0.404540  0.133469  0.377450   
obscene        0.005868  0.677491      0.404540  1.000000  0.149874  0.744685   
threat        -0.002872  0.162967      0.133469  0.149874  1.000000  0.157534   
insult         0.003664  0.648330      0.377450  0.744685  0.157534  1.000000   
identity_hate  0.001950  0.259124      0.193385  0.287794  0.123971  0.331922   

               identity_hate  
id                  0.001950  
toxic               0.259124  
severe_toxic        0.193385  
obscene             0.287794  
threat              0.123971  
insult              0.331922  
identity_hate       1.000000

In [9]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB

/opt/conda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [10]:
df.head()

id                                       comment_text  toxic  \
0  22256635  Nonsense?  kiss off, geek. what I said is true...      1   
1  27450690  "\n\n Please do not vandalize pages, as you di...      0   
2  54037174  "\n\n ""Points of interest"" \n\nI removed the...      0   
3  77493077  Asking some his nationality is a Racial offenc...      0   
4  79357270  The reader here is not going by my say so for ...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [11]:
new_df = df[['id','comment_text', 'insult']]

In [12]:
new_df

id                                       comment_text  insult
0          22256635  Nonsense?  kiss off, geek. what I said is true...       0
1          27450690  "\n\n Please do not vandalize pages, as you di...       0
2          54037174  "\n\n ""Points of interest"" \n\nI removed the...       0
3          77493077  Asking some his nationality is a Racial offenc...       0
4          79357270  The reader here is not going by my say so for ...       0
5          82428052      Fried chickens \n\nIs dat sum fried chickens?       0
6          87311443  Why can you put English for example on some pl...       0
7         114749757  Guy Fawkes \n\nim a resident in bridgwater and...       0
8         138560519  as far as nicknames go this article is embarra...       0
9         139353149  Woodland Meadows\nGood to hear that you correc...       0
10        150009866  "\n\nWell I just finished a good bit of editin...       0
11        152276337  Discussion should take place on the article ta...       0
12        153331729  Uh oh, you called my bluff. I am intimidated b...       0
13        153600803  "\nWe should also contact the living descendan...       0
14        154186883  " May 2008 (UTC)\n\nNotability of Your New Hea...       0
15        161894108  "\n\nWhile I agree that this article isn't FA ...       0
16        169740962  a Turkish citizen and him having received an a...       0
17        178084608  Please explain why censorship of quality addit...       0
18        208005265  In any case, this edit war will last forever. ...       0
19        224733383  "\n\n ""Vandalism"" of George Washington \n\nW...       0
20        225701312  Why hasn't Alitalia been removed rom the allia...       0
21        237279459  "\n\n Another AfD stats example \n\nI hope you...       0
22        254015372  "\nI will ;). How about... ah, I've got nothin...       0
23        280570905  ":I have moved some tedious detail in ""Survey...       0
24        284253328  @AnnieHall, what separates this from capitalis...       0
25        287371884  .  and its also not random, it was the first c...       0
26        293668009  "\nThe Graceful Slick....\nIs non other than a...       0
27        300891545  "====Regarding edits made during December 2 20...       0
28        307040060  "::The section is now called ""Discrepancies a...       0
29        340940431  "\n\n Smackdown! \n\nGood smackdown on Qatar, ...       0
...             ...                                                ...     ...
95821  999674711016  Gods. I'm an Anglo-Norman-ist, really, not an ...       0
95822  999677373048  "==T. COTTON LETTER TO THE AYATOLLAHS OF IRAN=...       0
95823  999693619845  Much appreciated \n\nThank you! Yours is my fi...       0
95824  999714130533  I do apologize once more to you for my unkind ...       0
95825  999716611707  It has been confirmed that Raul has joined FC ...       0
95826  999731184003  "\nThat an article is ""more than a definition...       0
95827  999741263322  Calling someone the archetypical unscientific ...       0
95828  999744390044  Just pointing out that if you intend to keep a...       0
95829  999749161210  I'm sorry for not noticing that on the article...       0
95830  999776197636  Can I just say, no-one cares about your opinio...       0
95831  999781781533  See Wikipedia:Administrators#Misuse_of_adminis...       0
95832  999825778693  December 2010\nPlease stop the foolish edits t...       0
95833  999829405247        Another Unblock Request \n\n 137.240.136.80       0
95834  999856640855                   so this can finally be over with       0
95835  999883234532  Oh, okay. Fair enough, then. Thanks for making...       0
95836  999887342595  "\nI believe you're out of line. You're specul...       0
95837  999888096837     , 22 April 2007 (UTC)\n\nSecond-hander.  21:45       0
95838  999898414104         "\nIt's staying. Let's move on.  Corbett "       0
95839  999903896729  "\n\n Conflict of Interest \n\nPm_shef: This i

In [13]:
new_df.describe()

id        insult
count  9.585100e+04  95851.000000
mean   4.994359e+11      0.049713
std    2.890136e+11      0.217352
min    2.225664e+07      0.000000
25%    2.473437e+11      0.000000
50%    5.001297e+11      0.000000
75%    7.501088e+11      0.000000
max    9.999882e+11      1.000000

In [14]:
df_x=new_df["comment_text"]
df_y=new_df["insult"]

In [15]:
cv1 = CountVectorizer()

In [16]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [17]:
x_traincv=cv1.fit_transform(x_train)

In [18]:
cv1.get_feature_names()

['00',
 '000',
 '0000',
 '000000',
 '00000000',
 '000002',
 '000002000004000008000016',
 '0000030422',
 '000023405011',
 '00004',
 '00007632',
 '000080',
 '00008b',
 '00009c',
 '0000z',
 '0001',
 '0003',
 '000319821',
 '0003º',
 '000_bucks',
 '000ft',
 '000hz',
 '000km',
 '000lb',
 '000s',
 '000th',
 '000z',
 '001',
 '0010',
 '0010steve',
 '0011',
 '0015',
 '0016',
 '0017',
 '002',
 '0020143',
 '0028',
 '002912',
 '00293',
 '003',
 '0032',
 '0034',
 '0037',
 '003_resize',
 '004',
 '0042',
 '0049703',
 '005',
 '005113',
 '0052',
 '0055',
 '0055bb',
 '0058',
 '006',
 '0060882417',
 '0062700674',
 '006400',
 '007',
 '007191',
 '007damianfalco',
 '008',
 '009',
 '009146',
 '009600',
 '0099ff',
 '00am',
 '00dd00',
 '00ff00',
 '00frodo',
 '00j0ail',
 '00pm',
 '00utc',
 '01',
 '010',
 '0100',
 '010001',
 '0101',
 '0101chiuwy',
 '0101nghk',
 '0101nialeung06',
 '010651',
 '011',
 '0110',
 '0111',
 '0118',
 '012',
 '0123',
 '0127',
 '013',
 '013078',
 '013353',
 '01384402728',
 '014',
 '0143',
 

In [19]:
a=x_traincv.toarray()

In [20]:
a[0]


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
cv1.inverse_transform(a[0])

[array(['about', 'absolutely', 'and', 'anywhere', 'be', 'bit', 'cid',
        'demonstrate', 'do', 'else', 'first', 'friend', 'hand', 'in',
        'incompetent', 'know', 'knowledge', 'love', 'military', 'pussy',
        'quite', 'some', 'somebody', 'stationed', 'that', 'the', 'to',
        'too', 'unit', 'wasn', 'with', 'would', 'yes', 'you'],
       dtype='<U4955')]

In [22]:
x_train.iloc[0]

"Somebody too incompetent to be stationed anywhere else. Yes I do know quite a bit about the military and I would absolutely love to demonstrate that knowledge with you first-hand. I wasn't in some pussy CID unit friend."

In [23]:
x_testcv=cv1.transform(x_test)

In [24]:
x_testcv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
mnb = MultinomialNB()

In [26]:
y_train=y_train.astype('int')

In [27]:
y_train

52521    0
3296     0
46761    0
91123    0
5735     0
89686    0
6711     0
57727    0
54349    0
1567     0
88728    0
50193    0
47216    0
27953    1
56740    0
95116    0
29857    0
36224    0
41646    0
66643    0
66622    0
46836    1
91887    0
57917    0
60275    0
87089    0
22855    0
38247    0
29971    0
14373    0
        ..
88407    0
68538    0
11586    0
52785    0
85640    0
79221    0
4802     1
21990    0
30205    0
59814    0
57493    0
51733    0
25600    0
9603     0
67124    0
73706    0
7212     0
32616    0
46393    0
95159    0
20062    1
79981    0
73575    0
65276    0
94601    0
23346    0
11863    0
92599    0
73902    0
83066    0
Name: insult, Length: 76680, dtype: int64

In [28]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
testmessage=x_test.iloc[0]

In [30]:
predictions=mnb.predict(x_testcv)

In [31]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
a=np.array(y_test)

In [33]:
a

array([0, 0, 0, ..., 0, 0, 0])

In [34]:
count = 0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

In [35]:
count

18466

In [36]:
len(predictions)

19171

In [37]:
count/len(predictions)

0.9632257054926712

In [38]:
from sklearn.metrics import confusion_matrix


In [39]:
confusion_matrix(a, predictions)

array([[17996,   242],
       [  463,   470]])

In [40]:
from sklearn.metrics import precision_recall_fscore_support

In [41]:
precision_recall_fscore_support(a, predictions, average='micro')

(0.96322570549267117, 0.96322570549267117, 0.96322570549267117, None)

In [42]:
### looks good. but isnt!! class is too unbalanced. need to be smarter in getting the ones correct!